const express = require('express');
const { body } = require('express-validator');
const { register, login, me, logout } = require('../controllers/authController');
const { protect } = require('../middleware/authMiddleware');
const validate = require('../middleware/validationMiddleware');
const router = express.Router();
router.post('/register', [body('name').trim().notEmpty().withMessage('Name is required'), body('username').trim().isLength({ min: 3 }).withMessage('Username must be at least 3 characters'), body('email').isEmail().withMessage('Valid email is required'), body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters'), body('role').isIn(['client', 'freelancer']).withMessage('Role must be client or freelancer'), validate], register);
router.post('/login', [body('email').isEmail().withMessage('Valid email is required'), body('password').notEmpty().withMessage('Password is required'), validate], login);
router.get('/me', protect, me);
router.post('/logout', protect, logout);
module.exports = router;
